"""add_vector_search

Revision ID: 2057efef8762
Revises: 6fdc82060ffa
Create Date: 2025-11-26 18:37:04.379238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
import pgvector

# revision identifiers, used by Alembic.
revision: str = '2057efef8762'
down_revision: Union[str, Sequence[str], None] = '6fdc82060ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_chapters', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('daily_chapters', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('daily_chapters', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index(op.f('ix_daily_chapters_category'), 'daily_chapters', ['category'], unique=False)
    op.add_column('timeline', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('timeline', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('timeline', sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('timeline', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index(op.f('ix_timeline_category'), 'timeline', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_category'), table_name='timeline')
    op.drop_column('timeline', 'embedding')
    op.drop_column('timeline', 'entities')
    op.drop_column('timeline', 'category')
    op.drop_column('timeline', 'tags')
    op.drop_index(op.f('ix_daily_chapters_category'), table_name='daily_chapters')
    op.drop_column('daily_chapters', 'embedding')
    op.drop_column('daily_chapters', 'category')
    op.drop_column('daily_chapters', 'tags')
    # ### end Alembic commands ###
