"""add_production_hardening

Revision ID: 2c6d12801b2c
Revises: 2057efef8762
Create Date: 2025-11-26 19:08:44.148708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c6d12801b2c'
down_revision: Union[str, Sequence[str], None] = '2057efef8762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_chapters', sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('daily_chapters', sa.Column('embedding_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('daily_chapters', sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='ready'))
    op.add_column('sessions', sa.Column('processing_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='ready'))
    op.add_column('timeline', sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('timeline', sa.Column('embedding_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline', 'embedding_version')
    op.drop_column('timeline', 'embedding_model')
    op.drop_column('sessions', 'processing_status')
    op.drop_column('daily_chapters', 'processing_status')
    op.drop_column('daily_chapters', 'embedding_version')
    op.drop_column('daily_chapters', 'embedding_model')
    # ### end Alembic commands ###
