"""Initial migration

Revision ID: 39504e846853
Revises: 
Create Date: 2025-11-20 17:01:23.666236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '39504e846853'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline_activities')
    op.add_column('timeline', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('timeline', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('timeline', sa.Column('activity', sa.String(), nullable=False))
    op.add_column('timeline', sa.Column('project', sa.String(), nullable=True))
    op.add_column('timeline', sa.Column('notes', sa.String(), nullable=True))
    op.alter_column('timeline', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_timeline_session_id'), 'timeline', ['session_id'], unique=False)
    op.drop_constraint(op.f('timeline_prompt_version_id_fkey'), 'timeline', type_='foreignkey')
    op.drop_column('timeline', 'summary')
    op.drop_column('timeline', 'prompt_version_id')
    op.drop_column('timeline', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('embedding', Vector(dim=1536), autoincrement=False, nullable=True))
    op.add_column('timeline', sa.Column('prompt_version_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('timeline', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('timeline_prompt_version_id_fkey'), 'timeline', 'prompts', ['prompt_version_id'], ['id'])
    op.drop_index(op.f('ix_timeline_session_id'), table_name='timeline')
    op.alter_column('timeline', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('timeline', 'notes')
    op.drop_column('timeline', 'project')
    op.drop_column('timeline', 'activity')
    op.drop_column('timeline', 'end_time')
    op.drop_column('timeline', 'start_time')
    op.create_table('timeline_activities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('activity', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('timeline_activities_pkey'))
    )
    # ### end Alembic commands ###
