"""add_file_attachments

Revision ID: 479c58aed83c
Revises: c1d2e3f4g5h6
Create Date: 2025-12-07 16:06:53.249372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '479c58aed83c'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4g5h6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_attachments',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('stored_path', sa.String(), nullable=False),
        sa.Column('mime_type', sa.String(), nullable=False),
        sa.Column('size_bytes', sa.Integer(), nullable=False),
        sa.Column('content_hash', sa.String(), nullable=False),
        
        # Links
        sa.Column('event_id', sa.Uuid(), nullable=True),
        sa.Column('timeline_id', sa.Uuid(), nullable=True),
        
        # Categorization
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        
        # Rich Metadata
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('technical_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        
        # Vector Search
        sa.Column('embedding', Vector(dim=768), nullable=True),
        sa.Column('embedding_model', sa.String(), nullable=True),
        
        # Status
        sa.Column('is_processed', sa.Boolean(), nullable=False),
        
        # Timestamps
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_attachments_content_hash'), 'file_attachments', ['content_hash'], unique=False)
    op.create_index(op.f('ix_file_attachments_event_id'), 'file_attachments', ['event_id'], unique=False)
    op.create_index(op.f('ix_file_attachments_timeline_id'), 'file_attachments', ['timeline_id'], unique=False)
    op.create_index(op.f('ix_file_attachments_category'), 'file_attachments', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_attachments_category'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_timeline_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_event_id'), table_name='file_attachments')
    op.drop_index(op.f('ix_file_attachments_content_hash'), table_name='file_attachments')
    op.drop_table('file_attachments')
    # ### end Alembic commands ###
