"""add_client_timezone_column

Revision ID: 51ffcd41017e
Revises: 88c402948ecf
Create Date: 2025-11-20 19:54:39.799061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51ffcd41017e'
down_revision: Union[str, Sequence[str], None] = '88c402948ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_logs', sa.Column('client_timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_logs', 'client_timezone')
    # ### end Alembic commands ###
