"""add_session_timezone

Revision ID: 6fdc82060ffa
Revises: 7ae0bd174f75
Create Date: 2025-11-25 18:38:20.144983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6fdc82060ffa'
down_revision: Union[str, Sequence[str], None] = '7ae0bd174f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="UTC"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'timezone')
    # ### end Alembic commands ###
