"""add_timezone_support

Revision ID: 88c402948ecf
Revises: 39504e846853
Create Date: 2025-11-20 19:50:00.207193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88c402948ecf'
down_revision: Union[str, Sequence[str], None] = '39504e846853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='UTC'))
    op.add_column('raw_logs', sa.Column('client_timestamp', sa.DateTime(), nullable=True))
    op.add_column('timeline', sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='UTC'))
    op.drop_column('timeline', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('timeline', 'timezone')
    op.drop_column('raw_logs', 'client_timestamp')
    op.drop_column('events', 'timezone')
    # ### end Alembic commands ###
