"""update_vector_dimensions

Revision ID: b7921b6d8f0b
Revises: 2c6d12801b2c
Create Date: 2025-11-26 21:28:35.398132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'b7921b6d8f0b'
down_revision: Union[str, Sequence[str], None] = '2c6d12801b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clear existing embeddings as they are incompatible with the new dimension
    op.execute("UPDATE daily_chapters SET embedding = NULL")
    op.execute("UPDATE timeline SET embedding = NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('daily_chapters', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    op.alter_column('timeline', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Clear existing embeddings as they are incompatible with the new dimension
    op.execute("UPDATE daily_chapters SET embedding = NULL")
    op.execute("UPDATE timeline SET embedding = NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    op.alter_column('daily_chapters', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=3072),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###
