"""Add device table

Revision ID: 635014d87f61
Revises: 477d84ba947f
Create Date: 2025-08-18 18:01:08.913766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '635014d87f61'
down_revision: Union[str, Sequence[str], None] = '477d84ba947f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('encrypted_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('device_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encrypted_api_key')
    )
    op.create_index(op.f('ix_device_name'), 'device', ['name'], unique=True)
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['extension_id'], ['extension.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extension_id', 'slug', name='uq_actor_extension_slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    op.drop_index(op.f('ix_device_name'), table_name='device')
    op.drop_table('device')
    # ### end Alembic commands ###
