"""Finish schema

Revision ID: b872d2e04e4a
Revises: 635014d87f61
Create Date: 2025-08-18 18:19:40.113014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b872d2e04e4a'
down_revision: Union[str, Sequence[str], None] = '635014d87f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- MANUAL FIX: DEFINE AND MANAGE ENUM TYPES ---
# Define Python representations of our ENUM types. `create_type=False` tells
# SQLAlchemy not to issue CREATE statements automatically; we will control it.
actor_type_enum = postgresql.ENUM('SOURCE', 'PROCESSOR', 'ENRICHER', 'BATCH_WORKER', 'AGENT', name='actortype', create_type=False)
ai_provider_type_enum = postgresql.ENUM('REMOTE_API', 'LOCAL_MANAGED', name='aiprovidertype', create_type=False)
# --- END MANUAL FIX ---


def upgrade() -> None:
    """Upgrade schema."""
    # --- MANUAL FIX: CREATE ENUM TYPES BEFORE USE ---
    # Manually create the ENUM types in the database before any tables use them.
    actor_type_enum.create(op.get_bind())
    ai_provider_type_enum.create(op.get_bind())
    # --- END MANUAL FIX ---

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aiprovider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # Use our defined variable for cleanliness
    sa.Column('provider_type', ai_provider_type_enum, nullable=False),
    sa.Column('encrypted_credentials', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_path_or_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_slug')
    )
    # ... (the rest of the autogenerated file is largely correct) ...
    op.create_table('eventtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_extension_id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['owner_extension_id'], ['extension.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_extension_id', 'slug', name='uq_event_type_owner_slug')
    )
    op.create_table('prompttemplate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_extension_id', sa.Integer(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('template_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_extension_id'], ['extension.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_extension_id', 'slug', name='uq_prompt_template_owner_slug')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processor_actor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('superseded_by_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_type_id'], ['eventtype.id'], ),
    sa.ForeignKeyConstraint(['processor_actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_end_time'), 'event', ['end_time'], unique=False)
    op.create_index(op.f('ix_event_start_time'), 'event', ['start_time'], unique=False)
    op.create_table('rawlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_actor_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['source_actor_id'], ['actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actorprocessinglog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('actor_version_at_processing', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_log_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['raw_log_id'], ['rawlog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aiusagelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('ai_provider_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('call_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['ai_provider_id'], ['aiprovider.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventmetadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventrawloglink',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('raw_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['raw_log_id'], ['rawlog.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'raw_log_id')
    )
    op.create_table('eventembedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('ai_usage_log_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['ai_usage_log_id'], ['aiusagelog.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_usage_log_id'),
    sa.UniqueConstraint('event_id', 'actor_id', name='uq_event_embedding_actor')
    )
    op.create_table('synthesisreport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('report_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ai_usage_log_id', sa.Integer(), nullable=True),
    sa.Column('superseded_by_report_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ),
    sa.ForeignKeyConstraint(['ai_usage_log_id'], ['aiusagelog.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_report_id'], ['synthesisreport.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ai_usage_log_id')
    )
    op.create_table('synthesiseventlink',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['synthesisreport.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'event_id')
    )
    op.alter_column('actor', 'actor_type',
           existing_type=sa.VARCHAR(),
           type_=actor_type_enum,
           existing_nullable=False,
           postgresql_using='actor_type::actortype') # <-- THE FINAL FIX
    op.add_column('device', sa.Column('client_metadata', sa.JSON(), nullable=True))
    # Note: Alembic sometimes gets confused about renames vs drop/add.
    # This might need a manual check if `device_metadata` was the old column name.
    # op.drop_column('device', 'device_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('device', sa.Column('device_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('device', 'client_metadata')
    op.alter_column('actor', 'actor_type',
           existing_type=actor_type_enum,
           type_=sa.VARCHAR(),
           existing_nullable=False,
           postgresql_using='actor_type::text')
    op.drop_table('synthesiseventlink')
    op.drop_table('synthesisreport')
    op.drop_table('eventembedding')
    op.drop_table('eventrawloglink')
    op.drop_table('eventmetadata')
    op.drop_table('aiusagelog')
    op.drop_table('actorprocessinglog')
    op.drop_table('rawlog')
    op.drop_index(op.f('ix_event_start_time'), table_name='event')
    op.drop_index(op.f('ix_event_end_time'), table_name='event')
    op.drop_table('event')
    op.drop_table('prompttemplate')
    op.drop_table('eventtype')
    op.drop_table('aiprovider')
    # ### end Alembic commands ###

    # --- MANUAL FIX: DROP ENUM TYPES AFTER THEY ARE NO LONGER USED ---
    # Manually drop the ENUM types from the database.
    actor_type_enum.drop(op.get_bind())
    ai_provider_type_enum.drop(op.get_bind())
    # --- END MANUAL FIX ---